import React from 'react';
import { motion } from 'motion/react';

export default function Showcase() {
    return (
        <motion.section
            key="showcase"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -20 }}
            className="px-6 max-w-7xl mx-auto pt-10"
        >
            <div className="mb-16 text-center">
                <h2 className="text-5xl font-serif font-bold mb-4">Concept Showcase</h2>
                <p className="text-black/50 max-w-2xl mx-auto">Explore visionary architectural concepts generated by our community of designers and architects.</p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                {[
                    { title: "The Obsidian Monolith", type: "Cultural", style: "Brutalist", img: "https://picsum.photos/seed/arch1/800/600" },
                    { title: "Ethereal Canopy", type: "Public Space", style: "Biophilic", img: "https://picsum.photos/seed/arch2/800/600" },
                    { title: "Kinetic Pavilion", type: "Installation", style: "Parametric", img: "https://picsum.photos/seed/arch3/800/600" },
                    { title: "Vertical Oasis", type: "Residential", style: "Minimalist", img: "https://picsum.photos/seed/arch4/800/600" },
                    { title: "The Glass Nexus", type: "Commercial", style: "Modernist", img: "https://picsum.photos/seed/arch5/800/600" },
                    { title: "Subterranean Library", type: "Educational", style: "Vernacular", img: "https://picsum.photos/seed/arch6/800/600" }
                ].map((item, i) => (
                    <div key={i} className="group cursor-pointer">
                        <div className="relative aspect-[4/3] overflow-hidden rounded-2xl mb-4 bg-arch-slate">
                            {/* eslint-disable-next-line @next/next/no-img-element */}
                            <img
                                src={item.img}
                                alt={item.title}
                                className="object-cover w-full h-full transition-transform duration-700 group-hover:scale-110"
                                referrerPolicy="no-referrer"
                            />
                            <div className="absolute inset-0 bg-black/20 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center">
                                <span className="px-4 py-2 bg-white text-black text-xs font-bold uppercase tracking-widest rounded-full">View Concept</span>
                            </div>
                        </div>
                        <div className="flex justify-between items-start">
                            <div>
                                <h3 className="font-serif text-xl font-bold">{item.title}</h3>
                                <p className="text-xs text-black/40 uppercase tracking-widest mt-1">{item.type} • {item.style}</p>
                            </div>
                        </div>
                    </div>
                ))}
            </div>
        </motion.section>
    );
}
